# Introduction to Torch

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



1.12.1


# Intro to Tensors

In [9]:
# scalar (0D 1 number)
scalar = torch.tensor(69)
scalar 

tensor(69)

In [10]:
scalar.ndim 

0

In [11]:
# convert tensor back to Python int
scalar.item()
scalar

tensor(69)

In [12]:
# vector (1D more than 1 number)
vector = torch.tensor([4,2])
vector # a row

tensor([4, 2])

In [13]:
# MATRIX (2D)
MATRIX = torch.tensor([[4,2],
                        [6,9]])
MATRIX # a row by column matrix

tensor([[4, 2],
        [6, 9]])

In [34]:
# TENSOR (3D but can be any dimension)
TENSOR = torch.tensor([[[4,2], # dim = 0 is first bracket
                        [6,9], # dim = 1 is second bracket rows
                        [1,2],]]) # dim = 2 is third bracket columns and so on
TENSOR 

tensor([[[4, 2],
         [6, 9],
         [1, 2]]])

In [35]:
TENSOR.ndim 

3

In [36]:
# depth, rows and columns 
TENSOR.shape # Think of depth as another dataset with the same rows and columns but distinct values

torch.Size([1, 3, 2])

In [37]:
# select first element of first row > first depth > first row > first column
TENSOR[0,0,0]

tensor(4)

In [24]:
# select a row
TENSOR[0,1]

tensor([6, 9])

## Random Tensors
- Important!!! as many N.Ns starts with full range of random numbers and then adjust those numbers to fit the range of the data.
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [41]:
# create random tensor with 4 rows and 2 columns
random_tensor = torch.rand(2,4,2)
random_tensor

tensor([[[0.7121, 0.0550],
         [0.2322, 0.2525],
         [0.2769, 0.7943],
         [0.6566, 0.6972]],

        [[0.6116, 0.1309],
         [0.2386, 0.6064],
         [0.6116, 0.9966],
         [0.7329, 0.1136]]])

In [46]:
# create a random tensor  with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (RGB) // color channels can also placed first (3,224,224)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros & Ones Tensor

In [50]:
# create a tensor of zeros
zeros = torch.zeros(size = (4, 2))
zeros, zeros.dtype

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]),
 torch.float32)

In [51]:
ones = torch.ones(size = (4, 2))
ones, ones.dtype

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]),
 torch.float32)

## Create a range of tensors and tensors-like

In [55]:
# create a tensor range 
range_tensor = torch.arange(start = 0, end = 11, step = 1,)
range_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
# creating tensors like 
zeros_like = torch.zeros_like(input=range_tensor)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

In [80]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device="cuda", # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations perfromed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cuda', index=0))

In [77]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=torch.float16, device="cuda", requires_grad=False)
float_16_tensor.shape, float_16_tensor.dtype, float_16_tensor.device

(torch.Size([3]), torch.float16, device(type='cuda', index=0))

In [78]:
float_16_tensor * float_32_tensor # sometimes this will give an error 

tensor([ 9., 36., 81.], device='cuda:0')

## Getting information from tensors
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

- shape - what shape is the tensor? (some operations require specific shape rules)
- dtype - what datatype are the elements within the tensor stored in?
- device - what device is the tensor stored on? (usually GPU or CPU).

Let's create a random tensor and find out details about it.

In [81]:
# Create a tensor
some_tensor = torch.rand(4, 2)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7390, 0.7758],
        [0.8277, 0.7664],
        [0.0974, 0.7399],
        [0.7621, 0.9065]])
Shape of tensor: torch.Size([4, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [84]:
%%time
tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device="cuda", # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations perfromed on the tensor are recorded 

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 46.9 ms
Wall time: 567 ms


tensor(126., device='cuda:0')

## Common Error Shape errors

In [13]:
tensor_A = torch.rand(3, 2)
tensor_B = torch.rand(3, 2)


tensor_A, tensor_B

(tensor([[0.0075, 0.1482],
         [0.4144, 0.7209],
         [0.4068, 0.2915]]),
 tensor([[0.6979, 0.1383],
         [0.6628, 0.7056],
         [0.0502, 0.5108]]))

In [14]:
%%time 
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [16]:
# transpoe that bish
tensor_B.T, 

(tensor([[0.6979, 0.6628, 0.0502],
         [0.1383, 0.7056, 0.5108]]),)